// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $advanced from './routes/advanced.tsx';
import * as $for_acl2_power_users from './routes/for-acl2-power-users.tsx';
import * as $index from './routes/index.tsx';
import * as $msort from './routes/msort.tsx';
import * as $Try from './islands/Try.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/advanced.tsx': $advanced,
    './routes/for-acl2-power-users.tsx': $for_acl2_power_users,
    './routes/index.tsx': $index,
    './routes/msort.tsx': $msort,
  },
  islands: {
    './islands/Try.tsx': $Try,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
